name: TestPlugin
version: 1.0
main: com.kmsichi.main.TestPlugin
api-version: 1.20
commands:
  testinv:
    description: '테스트 인벤토리'
    aliases:
      - ti
  닉네임:
    description: '닉네임 관리'
    aliases:
      - 닉넴
  스탯:
    description: '스탯 분배창'
    aliases:
      - tmxot
      - stat